"""Run external job_automation scripts (final_json, graph_creation, embed_nodes)."""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from app.core.config import settings


class JobAutomationPipelineService:
    """Wrapper around user-provided automation scripts."""

    def __init__(self) -> None:
        self.base_dir = Path(settings.JOB_AUTOMATION_DIR).resolve()
        self.timeout_seconds = int(settings.JOB_SCRIPT_TIMEOUT_SECONDS)
        self.python_executable = settings.JOB_PYTHON_EXECUTABLE.strip() or sys.executable

        self.final_json_script = self.base_dir / "final_json.py"
        self.graph_creation_script = self.base_dir / "graph_creation.py"
        self.embed_nodes_script = self.base_dir / "embed_nodes.py"

        self.combined_path = self.base_dir / "ocr_response_combined.json"
        self.combined_fixed_path = self.base_dir / "ocr_response_combined_fixed.json"
        self.output_path = self.base_dir / "output.json"

    def _ensure_scripts(self) -> None:
        for path in [self.final_json_script, self.graph_creation_script, self.embed_nodes_script]:
            if not path.exists():
                raise FileNotFoundError(f"Automation script not found: {path}")

    def _run(self, args: list[str], *, env: dict[str, str] | None = None) -> dict[str, Any]:
        merged_env = os.environ.copy()
        # Set UTF-8 encoding for subprocess to handle Unicode characters on Windows
        merged_env["PYTHONIOENCODING"] = "utf-8"
        if env:
            merged_env.update(env)

        completed = subprocess.run(
            args,
            cwd=str(self.base_dir),
            env=merged_env,
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=self.timeout_seconds,
            check=False,
        )
        if completed.returncode != 0:
            raise RuntimeError(
                f"Command failed ({completed.returncode}): {' '.join(args)}\n"
                f"STDOUT:\n{completed.stdout}\nSTDERR:\n{completed.stderr}"
            )
        return {"stdout": completed.stdout, "stderr": completed.stderr}

    def write_ocr_files(
        self,
        *,
        combined_payload: dict[str, Any],
        combined_fixed_payload: dict[str, Any],
    ) -> dict[str, str]:
        """Write OCR intermediate files to job_automation directory."""
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self.combined_path.write_text(
            json.dumps(combined_payload, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        self.combined_fixed_path.write_text(
            json.dumps(combined_fixed_payload, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        return {
            "ocr_response_combined": str(self.combined_path),
            "ocr_response_combined_fixed": str(self.combined_fixed_path),
        }

    def run_final_json(self) -> dict[str, Any]:
        """Run final_json.py to generate output.json from combined_fixed OCR."""
        self._ensure_scripts()
        cmd = [
            self.python_executable,
            str(self.final_json_script),
            str(self.combined_fixed_path),
            str(self.output_path),
        ]
        return self._run(cmd)

    def read_output_json(self) -> dict[str, Any]:
        """Read output.json generated by final_json.py."""
        if not self.output_path.exists():
            raise FileNotFoundError(f"Expected output not found: {self.output_path}")

        data = json.loads(self.output_path.read_text(encoding="utf-8"))
        return data

    def run_graph_creation(self) -> dict[str, Any]:
        """Run graph_creation.py exactly as defined in job_automation."""
        self._ensure_scripts()
        cmd = [self.python_executable, str(self.graph_creation_script)]
        return self._run(cmd)

    def run_embed_nodes(self) -> dict[str, Any]:
        """Run embed_nodes.py exactly as defined in job_automation."""
        self._ensure_scripts()
        cmd = [self.python_executable, str(self.embed_nodes_script)]
        return self._run(cmd)
